---
- hosts: tor_relays
  roles:
    - role: basics
      tags: basics

- hosts: tor_unbound
  roles:
    - role: unbound
      tags: unbound

- hosts: tor_relays
  roles:
    - role: tor
      tags: tor

- hosts: tor_prometheus
  roles:
    - role: prometheus
      tags: prometheus
