---
- name: create node_exporter path
  file:
    path: "{{ node_exporter_path }}"
    state: directory

- name: download node_exporter
  get_url:
    url: "{{ node_exporter_url }}"
    dest: "{{ node_exporter_path }}/node_exporter.tgz"
    checksum: "sha256:{{ node_exporter_sha256 }}"
  register: archive

- name: extract node_exporter
  unarchive:
    src: "{{ node_exporter_path }}/node_exporter.tgz"
    dest: "{{ node_exporter_path }}"
    extra_opts: "--strip-components=1"
    remote_src: yes
  when: archive.changed
  notify: restart prometheus-node-exporter

- name: template prometheus-node-exporter.service
  template:
    src: prometheus-node-exporter.service
    dest: /etc/systemd/system/
  notify: restart prometheus-node-exporter

- name: enable prometheus-node-exporter service
  systemd:
    name: prometheus-node-exporter
    enabled: yes
    daemon_reload: yes
