---
node_exporter_url: "https://github.com/prometheus/node_exporter/releases/download/v0.18.1/node_exporter-0.18.1.linux-amd64.tar.gz"
node_exporter_sha256: "b2503fd932f85f4e5baf161268854bf5d22001869b84f00fd2d1f57b51b72424"
node_exporter_path: /opt/node_exporter
tor_exporter_url: "https://github.com/atx/prometheus-tor_exporter/releases/download/v0.4/prometheus-tor-exporter_0.4_all.deb"
tor_exporter_sha256: "18ff114b31dd26262872462f09ba12e81d33c1271468f56fe565fbe32a18f10e"
tor_exporter_instances:
  - name: default
    control_socket: /var/run/tor/control
    user: debian-tor
